name: CALVADOS3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8.0
  - pandas=2.0.3
  - mdtraj=1.9.7
  - openmm=7.6.0
  - python=3.8.16
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - pip=23.3.1
  - pdbfixer=1.8.1
  - numpy=1.23.5
  - pillow
  - pip:
      - deerpredict
      - networkx==3.1
      - protobuf==3.20.3
      - ray==2.0.0
      - matplotlib==3.6.2
      - notebook
